Add custom rule label and 3DS result input
maxmind/minfraud-api-ruby pull request #54
Opened 2021-08-18 20:14 UTC by kevcenteno

* Adds custom rule label to disposition object
* Adds 3DS result to credit card input
* Updates disposition.action docs to include "test" disposition

2021-08-18 20:58 UTC, horgh commented
Lemme know when it's ready for review!

2021-08-18 21:41 UTC, kevcenteno commented
Ready for review :smile_cat:

2021-08-18 22:18 UTC, horgh requested changes

2021-08-18 22:18 UTC, horgh commented on lib/minfraud/components/credit_card.rb
> +      # verification was successful, or `false` if the customer failed
I believe markdown does not work in these comments. `+false+` would. (Actually I think yard can be made to support markdown but I don't think ours is set up to do that? I'm not sure. Either way it is not working AFAICT).

2021-08-18 22:18 UTC, horgh commented on CHANGELOG.md
> +  `Minfraud::Components::CreditCard`.
These could probably benefit from including a bit more information about them. For example, "Adds support for the /credit_card/was_3d_secure_successful input. This is available by setting the was_3d_secure_successful attribute on Minfraud::Components::CreditCard" or something like that.

2021-08-18 22:18 UTC, horgh commented on lib/minfraud/components/credit_card.rb
> +      # or resulted in another outcome other than success or failure, do not
"an outcome other than success or failure" perhaps?

2021-08-19 14:48 UTC, kevcenteno commented
@horgh Ready for another round of review :mag:

2021-08-19 15:49 UTC, horgh approved these changes

2021-08-19 15:49 UTC, merged